name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  continuous-integration:
    strategy:
      fail-fast: false
      matrix:
        env:
          - library-version: 1.2.0-beta.8
            container-runtime-version: 2.2.5
            container-runtime: alpine3.9
            runtime: alpine-x64
            os-version: Alpine 3.9
          - library-version: 1.2.0-beta.8
            container-runtime-version: 2.2.5
            container-runtime: alpine3.8
            runtime: alpine-x64
            os-version: Alpine 3.8
          - library-version: 1.2.0-beta.8
            container-runtime-version: 2.2.5
            container-runtime: stretch-slim
            runtime: debian.9-x64
            os-version: Debian 9
          - library-version: 1.2.0-beta.8
            container-runtime-version: 2.2.5
            container-runtime: bionic
            runtime: ubuntu.18.04-x64
            os-version: Ubuntu 18.04
    runs-on: ubuntu-latest
    name: continuous-integration/github/${{ matrix.env.container-runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: "./build.sh"
        env:
          REMOTE_IMAGE: sqlstreamstore/server
          LIBRARY_VERSION: ${{ matrix.env.library-version }}
          CONTAINER_RUNTIME_VERSION: ${{ matrix.env.container-runtime-version }}
          CONTAINER_RUNTIME: ${{ matrix.env.container-runtime }}
          RUNTIME: ${{ matrix.env.runtime }}
      - name: Docker Login
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: thefringeninja/sqlstreamstore-server
